### ISSUE TITLE
Datensatz

### ISSUE THREAD

**Issue by larissaaaaaaaa** [Juse3/wissenschaftliches-Arbeiten-Gruppe-17#3]
Die Datei daten.csv wurde erneuert. Irgendwie lag sie nicht in der von uns gewünschten finalen Version vor. Nun wurde die erste Spalte entfernt und die letzte Spalte umbenannt.
Der aktuelle Datensatz befindet sich zur Zeit nur im Branch KevinUnrau-patch-1.
Also wenn ihr den Datensatz schon gespeichert habt, bitte einmal zum richtigen wechseln.

**Comment by KevinUnrau** [comment]
Problem ist jetzt nach dem "mergen" behoben.
